<?php

/**
 * @file
 * Code for the GSB Feature House Ads FPP feature.
 */

include_once 'gsb_feature_house_ads_fpp.features.inc';

/**
 * Implements hook_entity_alter().
 */
function gsb_feature_house_ads_fpp_entity_info_alter(&$entity_info) {
  $entity_info['fieldable_panels_pane']['bundles']['house_ads'] = array(
    'label' => t('House Ads'),
    'pane category' => t('GSB panes'),
    'pane top level' => TRUE, // set to true to make this show as a top level icon
    'admin' => array(
      'path' => 'admin/structure/fieldable-panels-panes/manage/%fieldable_panels_panes_type',
      'bundle argument' => 4,
      // Note that this has all _ replaced with - from the bundle name.
      'real path' => 'admin/structure/fieldable-panels-panes/manage/house-ads',
      'access arguments' => array('administer fieldable panels panes'),
    ),
  );
}

/**
 * Implements hook_preprocess_panels_pane
 */
function gsb_feature_house_ads_fpp_preprocess_panels_pane(&$vars) {
  if ($vars['pane']->type == 'fieldable_panels_pane' && $vars['content']['#bundle'] == 'house_ads') {
    $wrapper = entity_metadata_wrapper('fieldable_panels_pane', $vars['content']['#fieldable_panels_pane']);
    $style = $wrapper->field_house_ads_style->value();
    $vars['classes_array'][] = $style;
  }
}

/**
 * Implements hook_form_FORM_ID_alter
 */
function gsb_feature_house_ads_fpp_form_fieldable_panels_panes_fieldable_panels_pane_content_type_edit_form_alter(&$form, &$form_state, $form_id) {
  if (isset($form['field_house_ads_style'][$form['field_house_ads_style']['#language']]['#options'])) {
    $options = &$form['field_house_ads_style'][$form['field_house_ads_style']['#language']]['#options'];
    $options['_none'] = '- Select a style -';
  }
}