<?php

/**
 * @file
 * Code for the GSB Feature House Ads feature.
 */

include_once 'gsb_feature_house_ads.features.inc';

/**
 * Implements hook_entity_alter().
 */
function gsb_feature_house_ads_entity_info_alter(&$entity_info) {
  $entity_info['fieldable_panels_pane']['bundles']['house_ads'] = array(
    'label' => t('House Ads'),
    'pane category' => t('GSB panes'),
    'admin' => array(
      'path' => 'admin/structure/fieldable-panels-panes/manage/%fieldable_panels_panes_type',
      'bundle argument' => 4,
      // Note that this has all _ replaced with - from the bundle name.
      'real path' => 'admin/structure/fieldable-panels-panes/manage/house-ads',
      'access arguments' => array('administer fieldable panels panes'),
    ),
  );
}

/**
 * Implements hook_preprocess_fieldable_panels_pane
 */
function gsb_feature_house_ads_preprocess_fieldable_panels_pane(&$vars) {
  if (isset($vars['elements']['#fieldable_panels_pane']->bundle) && $vars['elements']['#fieldable_panels_pane']->bundle == 'house_ads') {
    $wrapper = entity_metadata_wrapper('fieldable_panels_pane', $vars['elements']['#fieldable_panels_pane']);
    $style = $wrapper->field_style->value();
    $vars['classes_array'][] = 'house-add-style-' . $style;
  }
}
